name: CI/CD-IWeather

on:
  push:
    branches:
      - production

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    # create dependency on CI job
    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          # In the repository > settings > secrets and variables > actions > new secret
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      # EAS Submit Android (need access on Google Play and set secret on Github)
      # - name: Get config file
      #   # Secrets -> (send) -> GOOGLE_SERVICES_64 environment variable
      #   env:
      #     GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
      #   # Create a temporary json file to use for submitting (convert)
      #   run: |
      #     echo $GOOGLE_SERVICES_64 > google-services.json.b64
      #     base64 -d -i google-services.json.b64 > google-services.json

      - name: Build
        # Automatically creates the build and the action does't wait for the build to complete
        # See the build at https://expo.dev/
        run: eas build --platform android --profile production --non-interactive --no-wait
